# Generated by Django 5.1.2 on 2024-12-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.IntegerField(unique=True)),
                (
                    "room_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Basic", "Basic"),
                            ("Premium", "Premium"),
                            ("Executive", "Executive"),
                        ],
                        null=True,
                    ),
                ),
                ("floor", models.IntegerField(blank=True, null=True)),
                (
                    "bed_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Single", "Single"),
                            ("Double", "Double"),
                            ("Queen", "Queen"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "view",
                    models.CharField(
                        blank=True,
                        choices=[("Ocean", "Ocean"), ("City", "City")],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_code",
                    models.CharField(blank=True, max_length=5, null=True, unique=True),
                ),
                ("reserved_start_date", models.DateField(blank=True, null=True)),
                ("reserved_end_date", models.DateField(blank=True, null=True)),
                ("room_number", models.IntegerField(blank=True, null=True)),
                ("user_name", models.CharField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("APPROVED", "APPROVED"), ("In Review", "In Reivew")],
                        default="In Review",
                    ),
                ),
                (
                    "room_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bookings",
                        to="reservations.room",
                    ),
                ),
            ],
        ),
    ]
