# Generated by Django 5.1.2 on 2024-11-04 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('room_type', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Executive', 'Executive')], null=True)),
                ('floor', models.IntegerField(null=True)),
                ('bed_type', models.CharField(blank=True, choices=[('Single Bed', 'Single Bed'), ('Double Bed', 'Double Bed'), ('Queen Bed', 'Queen Bed')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('reserved_start_date', models.DateField(blank=True, null=True)),
                ('reserved_end_date', models.DateField(blank=True, null=True)),
                ('customer_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.customer')),
                ('room_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservations.room')),
            ],
        ),
    ]
