# Generated by Django 5.1.2 on 2024-11-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('Single', 'Single Bed'), ('Double', 'Double Bed'), ('Queen', 'Queen Bed')], null=True),
        ),
    ]
