# Generated by Django 5.1.2 on 2024-11-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_room_bed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='view',
            field=models.CharField(choices=[('Ocean', 'Ocean'), ('City', 'City')], null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('Single', 'Single Bed'), ('Double', 'Double Bed'), ('Queen', 'Queen Bed')], null=True),
        ),
    ]
