# Generated by Django 4.2.16 on 2024-10-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_bookings_booking_rename_rooms_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_date',
        ),
        migrations.AddField(
            model_name='room',
            name='reserved_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='reserved_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(null=True),
        ),
    ]
