# Generated by Django 5.1.2 on 2024-11-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_remove_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("APPROVED", "APPROVED"), ("In Review", "In Reivew")],
                default="In Review",
            ),
        ),
    ]
