# Generated by Django 5.1.2 on 2024-11-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_room_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='featured_image',
            new_name='room_image',
        ),
    ]
