# Generated by Django 5.1.2 on 2024-11-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_rename_featured_image_room_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="customer_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="room_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="bed_type",
            field=models.CharField(
                choices=[
                    ("Single Bed", "Single"),
                    ("Double Bed", "Double"),
                    ("Queen Bed", "Queen"),
                ],
                null=True,
            ),
        ),
    ]
