# Generated by Django 5.1.2 on 2024-11-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_alter_booking_customer_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
